MODEL:
  NUM_CLASSES: 5
  PRIORS:
    BOXES_PER_LOCATION: [4, 6 ,8 ,8 ,4 , 2]
    ASPECT_RATIOS: [[6], [6, 8], [6, 8,10], [6, 8, 10], [6], []]
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("voc_2007_trainval",)
  TEST: ("voc_2007_test", )
SOLVER:
  MAX_ITER: 1600
  LR_STEPS: [600]
  GAMMA: 0.1
  BATCH_SIZE: 16
  LR: 1e-4

OUTPUT_DIR: 'outputs/ocr_ssd300_v1'
